<?php ?>
<!--<div>-->
    <form class='login-form' method="post" action="auth.php">
        <div class="flex-row logo">
            <svg>
                <image href="./Images/logo.svg"></image>
            </svg>
            <h1>LOGO</h1>
        </div>
        <div class="flex-row">
            <input id="username" name="username" class='lf--input' placeholder='Your username' type='text'>
        </div>
        <div class="flex-row">
            <input id="password" name="password" class='lf--input' placeholder='Your password' type='password'>
        </div>
        <input class='lf--submit' type='submit' value='Sign Up'>
        <a class='lf--forgot' href='#'>Already throwing balls? Log In</a>
    </form>
<!--</div>-->

